parameters:
  - name: manualGitFlowFinish
    displayName: Manually finish git flow release process
    type: boolean
    default: true
  - name: createWorkItem
    displayName: Create work item to finish git flow release process
    type: boolean
    default: true
  - name: tpl_Enabled
    type: boolean
    default: true

stages:
  - stage: "Finish_Release"
    displayName: "Finish Release"
    condition: and(not(failed()), eq('${{ parameters.tpl_Enabled }}', 'true'))
    variables:
      - template: vars/vars-finish.yaml
    jobs:
      - job: CreateWorkItemForReleaseFinish
        displayName: "Create Work Item"
        pool: $(AGENT_POOL)
        steps:
          - task: mspremier.CreateWorkItem.CreateWorkItem-task.CreateWorkItem@1
            condition: eq('${{ parameters.createWorkItem }}', 'true')
            displayName: "Create work item"
            inputs:
              teamProject: NUCLEUS
              workItemType: "Product Backlog Item"
              title: "Autogenerated from integration-priorauth-code-deploy pipeline: Finish release"
              areaPath: 'NUCLEUS\Utilization Management'
              iterationPath: "Utilization Management@currentIteration"
              fieldMappings: |
                Description=As a PriorAuth Integration developer, I want to finish the release in git flow, so that the code deployed in this release is pushed to main and develop and a tag is created
                Acceptance Criteria=Given there is a release pipeline in progress, When all of the deployment and verification steps finish for all stages, Then the Git Flow release finish process should be executed manually be a developer
                Tags=AutoGenerated,Release
              associate: true
              assignedTo: $(Build.RequestedForId)

      - job: GitFlowReleaseFinish
        displayName: "Git Flow Release - Finish"
        pool: server
        steps:
          - task: ManualValidation@0
            displayName: "Execute Git Flow release finish process"
            condition: eq('${{ parameters.manualGitFlowFinish }}', 'true')
            timeoutInMinutes: 4320 # task times out in 3 days
            inputs:
              notifyUsers: ${{ variables.gitFlowReleaseFinishNotify }}
              instructions: "Manually verify git flow release finish steps in order to proceed."
              onTimeout: "resume" # it doesn't make sense to reject and fail the pipeline at this point. TODO: Create a work item automatically.
