# Parameters passed in from calling pipeline

parameters:
- name: tpl_Enabled
  type: boolean
  default: false
- name: tpl_Environment
  type: string
  default: ''

stages:
- stage: "Deploy_${{ parameters.tpl_Environment }}"
  displayName: "Deploy to ${{ parameters.tpl_Environment }}"
  condition: and(not(failed()), eq('${{ parameters.tpl_Enabled }}', true))
  variables:
  - template: vars/vars-${{ parameters.tpl_Environment }}.yaml
  jobs:
  - ${{ if eq(parameters.tpl_environment, 'stage') }}:
    - job: PausePipeline
      pool: server
      steps:
      - task: ManualValidation@0
        timeoutInMinutes: 1440 # task times out in 1 day
        inputs:
          notifyUsers: ${{ variables.pauseNotify }}
          instructions: 'Please resume the release in order to proceed.'
          onTimeout: 'timed out waiting for manual resume'

  - deployment: "Deploy_${{ parameters.tpl_Environment }}"
    ${{ if eq(parameters.tpl_environment, 'stage') }}:
      dependsOn: PausePipeline
    displayName: "Deploy to ${{ parameters.tpl_Environment }}"
    workspace:
      clean: all
    environment: ${{ variables.SERVICE_CONNECTION }} # ADO Environment Resource
    pool:
      name: $(AGENT_POOL)
    strategy:
      runOnce:
        deploy:
          steps:
          # Prevent the default download of all build artifacts, including cdk synth output and test results

          - script: |
              echo "Environment variables"
              echo "====================="
              env | sort
            displayName: 'Display Environment Variables'

          # =========================================================================================
          # Optional: Download only the DotnetApp artifiact from a related pipeline.
          #
          # By default, the deploy  task downloads all build artifacts, which includes
          # cdk synth output and test results. These additional artifacts are, in some cases, much
          # larger than the built application.
          #
          # To download only the build application(s), uncomment the following block and follow
          # the instructions for how to find your specific project and pipeline GUIDs. For NUCLEUS,
          # the project ID will always be the same.
          # ==========================================================================================
          # To get the project and pipeline IDs for the build pipeline triggering the deploy:
          # 1. Use the ADO web interface to edit the deploy pipeline.
          # 2. Add a Download Build Artifact task. Fill in the required fields for the ask and click add.
          # 3. Cut the text just added to the pipeline and paste it into this file.
          # 4. Cancel your edit in the ADO web interface
          # - download: none
          # - task: DownloadBuildArtifacts@0
          #   inputs:
          #     buildType: 'specific'
          #     project: 'ed70c3c9-3261-4ec9-828b-5d7d675b5053' # NUCLEUS Project
          #     pipeline: '572' #ID of csharp build pipeline
          #     specificBuildWithTriggering: true
          #     buildVersionToDownload: 'latest'
          #     downloadType: 'single'
          #     artifactName: '$(ARTIFACT_NAME)'
          #     downloadPath: '$(PIPELINE.WORKSPACE)/$(RESOURCE_PIPELINE_NAME)'

          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: '$(PIPELINE.WORKSPACE)/$(RESOURCE_PIPELINE_NAME)/**/*.zip'
              destinationFolder: '$(PIPELINE.WORKSPACE)/$(RESOURCE_PIPELINE_NAME)/$(ARTIFACT_NAME)'
              cleanDestinationFolder: false
              overwriteExistingFiles: true
            displayName: 'Extract Zipped Artifact'

          - task: AWSShellScript@1
            displayName: 'CDK Deploy'
            inputs:
              awsCredentials: ${{ variables.SERVICE_CONNECTION }}
              regionName: $(REGION_NAME)
              scriptType: filePath
              filePath: '$(INFRA_SCRIPTS_PATH)/deploy.sh'
              disableAutoCwd: true
