trigger:
- main
- develop

variables:
  NODE_VERSION: "22.11.0"
  CDK_VERSION: "2.1033.0"

# Queue Time Configuration Parameters
parameters:
- name: poolName
  displayName: Agent Pool
  type: string
  default: 'aws-cdk'  
  values:
  - 'aws-cdk'
- name: clean
  displayName: Checkout Clean
  type: boolean
  default: true
  values:
  - false
  - true

stages:
- stage: PublishBaseIntegrationPriorAuthNuget
  displayName: "Publish Base Integration PriorAuth Nuget Package"
  jobs:
  - job: Build
    displayName: "Package Build"
    pool:
      name: ${{parameters.poolName}}

    steps:
    # Checkout code and clean agent working dir
    - checkout: self
      clean: ${{ parameters.clean }}

    # Setup Env
    - script: |
        echo "Setting Up Env"
        chmod u+x ./scripts/cicd/infra/setenv.sh
        ./scripts/cicd/infra/setenv.sh
      workingDirectory: "$(Build.Repository.LocalPath)"
      displayName: "Setup Environment"

    # Display Current Environment Variables, sorted - Debugging Task
    - script: |
        env | sort
      displayName: 'Display Environment Variables'

    - task: UseDotNet@2
      displayName: 'Use .NET 10 SDK'
      inputs:
        packageType: 'sdk'
        version: '10.0.x'

    - script: |
        chmod u+x ./scripts/cicd/dotnet/pack.sh
        ./scripts/cicd/dotnet/pack.sh
      condition: succeeded()
      workingDirectory: "$(Build.Repository.LocalPath)"
      displayName: 'Build package'

    - task: NuGetAuthenticate@0
      condition: succeeded()
      displayName: 'NuGet Authenticate'
      inputs:
        forceReinstallCredentialProvider: true

    - task: DotNetCoreCLI@2
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
      displayName: 'Publish Integration PriorAuth Base Package to Test_Feed'
      continueOnError: true
      inputs:
        command: 'push'
        workingDirectory: "$(Build.Repository.LocalPath)"
        packagesToPush: '$(Build.StagingDirectory)/**/Integration.PriorAuth.*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: 'Test_Feed'
        allowPackageConflicts: true

    - task: DotNetCoreCLI@2
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
      displayName: 'Publish Integration PriorAuth Base Package to Enterprise_Feed'
      continueOnError: true
      inputs:
        command: 'push'
        workingDirectory: "$(Build.Repository.LocalPath)"
        packagesToPush: '$(Build.StagingDirectory)/**/Integration.PriorAuth.*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: 'Enterprise_Feed'
        allowPackageConflicts: true