# /aws-cdk-examples/csharp/api-cors-lambda-dynamo-dotnet-6/scripts/cicd/build.yaml

# =======================================================
# See README.md for links and callouts about
# ADO triggers, filters, and variable definitions.
# =======================================================

# NOTE: Main is built to retain artifacts and code coverage reports; however, this build occurs after the deploy of a release branch to production.

trigger:
  branches:
    include:
    - develop
    - release/*

variables:
- template: vars/vars-global.yaml
  parameters:
    tpl_type: 'Build'

# Runtime parameters for manual pipeline execution can only be defined in the main pipeline.yaml, not templates.
parameters:
- name: serviceConnection # ADO Service Connection Name
  displayName: ADO Service Connection Name
  default: "pod16-sandbox"
  values:
    - "pod16-sandbox"
    - "integration-dev"
    
- name: clean
  displayName: Clean agent working directory on checkout
  type: boolean
  default: true
  values:
  - false
  - true
  
- name: Postclean
  displayName: Post Completion Clean-up
  type: boolean
  default: true
  values:
  - false
  - true

stages:
- template: _template-build.yaml
  parameters:
    tpl_clean: ${{parameters.clean}}
    tpl_serviceConnection: ${{parameters.serviceConnection}}
    tpl_Postclean: ${{parameters.Postclean}}
    tpl_displayName: "Build ${{ variables['Build.SourceBranch'] }}"
