# /aws-cdk-examples/csharp/api-cors-lambda-dynamo-dotnet-6/scripts/cicd/deploy.yaml

# =======================================================
# See README.md for links and callouts about
# ADO triggers, filters, and variable definitions.
# =======================================================

trigger: none # Do not trigger on commits to a branch.

# Main is not included in branch triggers for gitflow. Release branches are deployed to production.

resources:
  pipelines:
  - pipeline: IntegrationPriorAuthCore # unique value that you can use to reference the pipeline resource later in this pipeline
    source: integration-priorauth-core-build # the source pipeline that produces an artifact
    project: NUCLEUS
    #tags:
    #- release-candidate
    trigger:
      branches:
        include:
        - release/*
        - feature/nick/*
      #tags:
      #- release-candidate

variables:
- template: vars/vars-global.yaml
  parameters:
    tpl_type: 'Deploy'

# ============================================
# See README.md Environment approvals section
# ============================================
stages:

# Test environment / release branches
- template: _template-deploy.yaml
  parameters:
      tpl_Enabled: ${{ startsWith(variables['Build.SourceBranch'], 'refs/heads/release/') }}
      tpl_Environment: "test"

# # Stage environment / release branches
# - template: _template-deploy.yaml
#   parameters:
#       tpl_Enabled: ${{ startsWith(variables['Build.SourceBranch'], 'refs/heads/release/') }}
#       tpl_Environment: "stage"

# # Production environment / release branches
# - template: _template-deploy.yaml
#   parameters:
#       tpl_Enabled: ${{ startsWith(variables['Build.SourceBranch'], 'refs/heads/release/') }}
#       tpl_Environment: "production"

- template: _template_release_finish.yaml
