<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <!-- Roll forward to future major versions of the netcoreapp as needed -->
    <RollForward>Major</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="nuget.config" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.CDK.Lib" Version="2.78.0" />
    <PackageReference Include="Constructs" Version="10.2.12" />
    <PackageReference Include="Nucleus.Nagpack" Version="1.1.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Base\Base.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="nuget.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <None Update="config.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
